# Source registry: source_id, type, endpoint, tier, role, region, auth, status.
# No fetching; only structure.
# Status: usable | needs_key | restricted | unconfirmed
# Use get_usable_connector_sources() for the first connector set (usable + needs_key only).

from typing import TypedDict


class SourceConfig(TypedDict, total=False):
    source_id: str
    name: str
    domain: str
    tier: int
    role: str
    source_type: str  # api | rss | rss_pattern
    endpoint_url: str
    status: str  # usable | needs_key | restricted | unconfirmed
    auth_required: bool
    auth_key_env: str
    region: str
    notes: str


# All sources: Usable/needs_key = build connectors; restricted/unconfirmed = registry only.
SOURCE_REGISTRY: list[SourceConfig] = [
    # ---- Tier 1: Core factual ----
    {
        "source_id": "guardian",
        "name": "The Guardian",
        "domain": "theguardian.com",
        "tier": 1,
        "role": "Core factual",
        "source_type": "api",
        "endpoint_url": "https://content.guardianapis.com/",
        "status": "needs_key",
        "auth_required": True,
        "auth_key_env": "GUARDIAN_API_KEY",
        "region": "western",
    },
    {
        "source_id": "bbc_news",
        "name": "BBC News",
        "domain": "bbc.com / bbc.co.uk",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/front_page/rss.xml",
        "status": "usable",
        "auth_required": False,
        "region": "western",
    },
    {
        "source_id": "ap",
        "name": "Associated Press",
        "domain": "apnews.com",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://apnews.com/rss/apf-topnews",
        "status": "disabled",
        "auth_required": False,
        "region": "western",
    },
    {
        "source_id": "abc_news_us",
        "name": "ABC News (US)",
        "domain": "abcnews.go.com",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://feeds.abcnews.com/abcnews/topstories",
        "status": "usable",
        "auth_required": False,
        "region": "western",
    },
    {
        "source_id": "deutsche_welle",
        "name": "Deutsche Welle",
        "domain": "dw.com",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://rss.dw.com/rdf/rss-en-all",
        "status": "usable",
        "auth_required": False,
        "region": "european",
    },
    {
        "source_id": "le_monde",
        "name": "Le Monde",
        "domain": "lemonde.fr",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://www.lemonde.fr/en/international/rss_full.xml",
        "status": "usable",
        "auth_required": False,
        "notes": "Pattern: append rss_full.xml to section URL for other sections",
        "region": "european",
    },
    {
        "source_id": "el_pais_english",
        "name": "El País English",
        "domain": "english.elpais.com / elpais.com",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://elpais.com/rss/elpais/inenglish.xml",
        "status": "usable",
        "auth_required": False,
        "region": "european",
    },
    # ---- Tier 1: Core factual + perspective ----
    {
        "source_id": "al_jazeera_english",
        "name": "Al Jazeera English",
        "domain": "aljazeera.com",
        "tier": 1,
        "role": "Core factual + perspective",
        "source_type": "rss",
        "endpoint_url": "https://www.aljazeera.com/xml/rss/all.xml",
        "status": "usable",
        "auth_required": False,
        "region": "middle_eastern",
    },
    {
        "source_id": "straits_times",
        "name": "The Straits Times",
        "domain": "straitstimes.com",
        "tier": 1,
        "role": "Core factual + perspective",
        "source_type": "rss",
        "endpoint_url": "https://www.straitstimes.com/news/world/rss.xml",
        "status": "usable",
        "auth_required": False,
        "region": "asia",
    },
    {
        "source_id": "scmp",
        "name": "South China Morning Post",
        "domain": "scmp.com",
        "tier": 1,
        "role": "Core factual + perspective",
        "source_type": "rss",
        "endpoint_url": "https://www.scmp.com/rss",
        "status": "usable",
        "auth_required": False,
        "notes": "Official RSS directory; exact section feed still to pick",
        "region": "asia",
    },
    {
        "source_id": "business_times_sg",
        "name": "The Business Times (Singapore)",
        "domain": "businesstimes.com.sg",
        "tier": 1,
        "role": "Core factual + perspective",
        "source_type": "rss",
        "endpoint_url": "https://www.businesstimes.com.sg/rss/top-stories",
        "status": "usable",
        "auth_required": False,
        "region": "business",
    },
    {
        "source_id": "abc_news_au",
        "name": "ABC News (Australia)",
        "domain": "abc.net.au",
        "tier": 1,
        "role": "Core factual + perspective",
        "source_type": "rss",
        "endpoint_url": "https://www.abc.net.au/news/feed/51120/rss.xml",
        "status": "usable",
        "auth_required": False,
        "notes": "RSS page confirmed; 51120 is one feed ID; exact feed URLs may need adjustment",
        "region": "asia",
    },
    {
        "source_id": "mail_guardian",
        "name": "Mail & Guardian",
        "domain": "mg.co.za",
        "tier": 1,
        "role": "Core factual + perspective",
        "source_type": "rss",
        "endpoint_url": "https://mg.co.za/rss-feeds/",
        "status": "usable",
        "auth_required": False,
        "notes": "Official RSS page; exact feed URLs to be extracted from page",
        "region": "other",
    },
    # ---- Tier 1: Additional expanded sources (US, UK, Europe, Middle East, India, Asia, Africa, Latin America) ----
    {
        "source_id": "nytimes",
        "name": "New York Times",
        "domain": "nytimes.com",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
        "status": "usable",
        "auth_required": False,
        "region": "western",
    },
    {
        "source_id": "washington_post",
        "name": "Washington Post",
        "domain": "washingtonpost.com",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://feeds.washingtonpost.com/rss/world",
        "status": "usable",
        "auth_required": False,
        "region": "western",
    },
    {
        "source_id": "npr",
        "name": "NPR",
        "domain": "npr.org",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://feeds.npr.org/1001/rss.xml",
        "status": "usable",
        "auth_required": False,
        "region": "western",
    },
    {
        "source_id": "wsj",
        "name": "Wall Street Journal",
        "domain": "wsj.com",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://feeds.a.dj.com/rss/RSSWorldNews.xml",
        "status": "usable",
        "auth_required": False,
        "region": "western",
    },
    {
        "source_id": "cbc_news",
        "name": "CBC News",
        "domain": "cbc.ca",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://www.cbc.ca/cmlink/rss-topstories",
        "status": "usable",
        "auth_required": False,
        "region": "western",
    },
    {
        "source_id": "sky_news",
        "name": "Sky News",
        "domain": "news.sky.com",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://feeds.skynews.com/feeds/rss/world.xml",
        "status": "usable",
        "auth_required": False,
        "region": "western",
    },
    {
        "source_id": "independent",
        "name": "The Independent",
        "domain": "independent.co.uk",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://www.independent.co.uk/news/world/rss",
        "status": "usable",
        "auth_required": False,
        "region": "western",
    },
    {
        "source_id": "telegraph",
        "name": "The Telegraph",
        "domain": "telegraph.co.uk",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://www.telegraph.co.uk/rss.xml",
        "status": "disabled",
        "auth_required": True,
        "region": "western",
    },
    {
        "source_id": "euronews",
        "name": "Euronews",
        "domain": "euronews.com",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://www.euronews.com/rss?level=theme&name=news",
        "status": "usable",
        "auth_required": False,
        "region": "european",
    },
    {
        "source_id": "politico_eu",
        "name": "Politico Europe",
        "domain": "politico.eu",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://www.politico.eu/feed/",
        "status": "usable",
        "auth_required": False,
        "region": "european",
    },
    {
        "source_id": "france24",
        "name": "France24",
        "domain": "france24.com",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://www.france24.com/en/rss",
        "status": "usable",
        "auth_required": False,
        "region": "european",
    },
    {
        "source_id": "spiegel",
        "name": "Der Spiegel",
        "domain": "spiegel.de",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://www.spiegel.de/international/index.rss",
        "status": "usable",
        "auth_required": False,
        "region": "european",
    },
    {
        "source_id": "el_mundo",
        "name": "El Mundo",
        "domain": "elmundo.es",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://e00-elmundo.uecdn.es/elmundo/rss/portada.xml",
        "status": "usable",
        "auth_required": False,
        "region": "european",
    },
    {
        "source_id": "corriere",
        "name": "Corriere della Sera",
        "domain": "corriere.it",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://xml2.corriereobjects.it/rss/homepage.xml",
        "status": "usable",
        "auth_required": False,
        "region": "european",
    },
    {
        "source_id": "arab_news",
        "name": "Arab News",
        "domain": "arabnews.com",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://www.arabnews.com/rss.xml",
        "status": "disabled",
        "auth_required": False,
        "region": "middle_eastern",
    },
    {
        "source_id": "times_of_israel",
        "name": "Times of Israel",
        "domain": "timesofisrael.com",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://www.timesofisrael.com/feed/",
        "status": "usable",
        "auth_required": False,
        "region": "middle_eastern",
    },
    {
        "source_id": "the_hindu",
        "name": "The Hindu",
        "domain": "thehindu.com",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://www.thehindu.com/news/national/?service=rss",
        "status": "usable",
        "auth_required": False,
        "region": "asia",
    },
    {
        "source_id": "indian_express",
        "name": "Indian Express",
        "domain": "indianexpress.com",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://indianexpress.com/feed/",
        "status": "usable",
        "auth_required": False,
        "region": "asia",
    },
    {
        "source_id": "nhk_world",
        "name": "NHK World",
        "domain": "nhk.or.jp",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://www3.nhk.or.jp/rss/news/cat0.xml",
        "status": "usable",
        "auth_required": False,
        "region": "asia",
    },
    {
        "source_id": "korea_herald",
        "name": "Korea Herald",
        "domain": "koreaherald.com",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "http://www.koreaherald.com/common_prog/rssdisp.php?ct=020000000000.xml",
        "status": "usable",
        "auth_required": False,
        "region": "asia",
    },
    {
        "source_id": "news24",
        "name": "News24",
        "domain": "news24.com",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://feeds.news24.com/articles/news24/TopStories/rss",
        "status": "usable",
        "auth_required": False,
        "region": "africa",
    },
    {
        "source_id": "daily_nation",
        "name": "Daily Nation",
        "domain": "nation.africa",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://nation.africa/rss",
        "status": "disabled",
        "auth_required": False,
        "region": "africa",
    },
    {
        "source_id": "folha",
        "name": "Folha de São Paulo",
        "domain": "folha.uol.com.br",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://feeds.folha.uol.com.br/internacional/en/world/rss091.xml",
        "status": "usable",
        "auth_required": False,
        "region": "latin_america",
    },
    {
        "source_id": "la_nacion",
        "name": "La Nación",
        "domain": "lanacion.com.ar",
        "tier": 1,
        "role": "Core factual",
        "source_type": "rss",
        "endpoint_url": "https://www.lanacion.com.ar/arc/outboundfeeds/rss/",
        "status": "usable",
        "auth_required": False,
        "region": "latin_america",
    },
    # ---- Tier 1: Restricted (registry only, no connector) ----
    {
        "source_id": "reuters",
        "name": "Reuters",
        "domain": "reuters.com",
        "tier": 1,
        "role": "Desired core factual",
        "source_type": "rss",
        "endpoint_url": "",
        "status": "restricted",
        "auth_required": False,
        "notes": "No open public RSS found; subscriptions/commercial access",
    },
    {
        "source_id": "financial_times",
        "name": "Financial Times",
        "domain": "ft.com",
        "tier": 1,
        "role": "Desired core factual",
        "source_type": "rss",
        "endpoint_url": "",
        "status": "restricted",
        "auth_required": False,
        "notes": "myFT RSS tied to account preferences",
    },
    # ---- Tier 1: Unconfirmed (registry only, no connector) ----
    {
        "source_id": "japan_times",
        "name": "The Japan Times",
        "domain": "japantimes.co.jp",
        "tier": 1,
        "role": "Desired Asia source",
        "source_type": "rss",
        "endpoint_url": "",
        "status": "unconfirmed",
        "auth_required": False,
        "notes": "RSS referenced in help/start pages; exact public feed not confirmed",
    },
    # ---- Tier 2: Discovery / recall ----
    {
        "source_id": "gdelt",
        "name": "GDELT",
        "domain": "gdeltproject.org",
        "tier": 2,
        "role": "Discovery / recall",
        "source_type": "api",
        "endpoint_url": "https://api.gdeltproject.org/api/v2/doc/doc",
        "status": "usable",
        "auth_required": False,
        "notes": "DOC API; query config TBD",
    },
    {
        "source_id": "newsapi",
        "name": "NewsAPI",
        "domain": "newsapi.org",
        "tier": 2,
        "role": "Discovery / recall",
        "source_type": "api",
        "endpoint_url": "https://newsapi.org/v2/",
        "status": "needs_key",
        "auth_required": True,
        "auth_key_env": "NEWSAPI_KEY",
        "notes": "Free tier limited",
    },
]


def get_source_registry() -> list[SourceConfig]:
    """Return the full source registry (all statuses)."""
    return SOURCE_REGISTRY


def get_usable_connector_sources() -> list[SourceConfig]:
    """Return only sources that should have production connectors built: status usable or needs_key."""
    return [s for s in SOURCE_REGISTRY if s["status"] in ("usable", "needs_key")]


def get_sources_by_status(status: str) -> list[SourceConfig]:
    """Return sources with the given status."""
    return [s for s in SOURCE_REGISTRY if s["status"] == status]


def get_region_and_name_for_source(source_id: str) -> tuple[str, str]:
    """Return (region, display_name) for source_id. Default ('other', source_id)."""
    for s in SOURCE_REGISTRY:
        if s.get("source_id") == source_id:
            return (s.get("region") or "other", s.get("name") or source_id)
    return ("other", source_id)
